apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repset-conv-temp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conv-temp
  template:
    metadata:
      labels:
        app: conv-temp
    spec:
      containers:
        - name: conv-temp-web
          image: alexandrebhte/conversao-temperatura:v1
          ports:
            - containerPort: 8080
      